apiVersion: apps/v1
kind: Deployment
metadata:
  name: Room
  labels:
    app: Room
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Room
  template:
    metadata:
      labels:
        app: Room
    spec:
      containers:
        - name: Room
          image: username/Room:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          env:
            - name: configurl
