apiVersion: apps/v1
kind: Deployment
metadata:
  name: Room
  labels:
    app: Room
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Room
  template:
    metadata:
      labels:
        app: Room
    spec:
      containers:
        - name: Room
          image: username/Room:latest
          ports:
            - containerPort: 8080
          env:
            - name: configurl
